import 'bootstrap/dist/css/bootstrap.min.css';
import './assets/css/poncho.css';
import './assets/css/roboto-fontface.css';
import 'font-awesome/css/font-awesome.css';
import './assets/css/style.css';
import 'react-block-ui/style.css';
import * as React from 'react';
import * as  ReactDOM from 'react-dom';
import {push} from 'react-router-redux';
import {createAppStore} from './AppStore';
import {initApiInterceptor} from './common/util/ApiInterceptor';
import {createAppRouter} from './AppRouter';
import {initSystem} from './reducer/sys';
import {detectCloseTab} from './common/util/DetectCloseTab';

ReactDOM.render(<div>Iniciando authenticación</div>, document.getElementById('content'));
const isLoggerEnabled = process.env.NODE_ENV !== 'production';
const store = createAppStore(true);
store.dispatch(initSystem());
initApiInterceptor(store);
detectCloseTab(store);
const router = createAppRouter(store);
ReactDOM.render(router, document.getElementById('content'));
store.dispatch(push('/'));
